# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46980635474e503c390cbf8758fa483ddd7991c95b7e38319d340296f7d59f22f9d61d1ef6074da0bf84a49035745d255928533c4ddedc44f78fa3d90e4d4229

test:
  secret_key_base: 0ec2ed7e71808250bb1f8db4f4df1f7bf180d7f4abec6a8e54f123b9e06e76905fa4935c922caa0d26c566ef3ca93fddab8fe708b84f02b597647e3adb6721d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
